//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.Eventing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.Eventing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length does not match.
        /// </summary>
        internal static string ERR_ARRAY_LENGTH_NOT_MATCH {
            get {
                return ResourceManager.GetString("ERR_ARRAY_LENGTH_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given class cannot be intercepted (is it sealed?).
        /// </summary>
        internal static string ERR_CANNOT_BE_INTERCEPTED {
            get {
                return ResourceManager.GetString("ERR_CANNOT_BE_INTERCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate event id.
        /// </summary>
        internal static string ERR_DUPLICATE_EVENT_ID {
            get {
                return ResourceManager.GetString("ERR_DUPLICATE_EVENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given flow id already exists.
        /// </summary>
        internal static string ERR_FLOW_ID_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERR_FLOW_ID_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to relese lock that doesn&apos;t belong to owner.
        /// </summary>
        internal static string ERR_FOREIGN_LOCK_RELEASE {
            get {
                return ResourceManager.GetString("ERR_FOREIGN_LOCK_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventized method may not return a value.
        /// </summary>
        internal static string ERR_HAS_RETVAL {
            get {
                return ResourceManager.GetString("ERR_HAS_RETVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid event id.
        /// </summary>
        internal static string ERR_INVALID_EVENT_ID {
            get {
                return ResourceManager.GetString("ERR_INVALID_EVENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid flow id.
        /// </summary>
        internal static string ERR_INVALID_FLOW_ID {
            get {
                return ResourceManager.GetString("ERR_INVALID_FLOW_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View layout changed since the last update.
        /// </summary>
        internal static string ERR_LAYOUT_MISMATCH {
            get {
                return ResourceManager.GetString("ERR_LAYOUT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed array.
        /// </summary>
        internal static string ERR_MALFORMED_ARRAY {
            get {
                return ResourceManager.GetString("ERR_MALFORMED_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed object.
        /// </summary>
        internal static string ERR_MALFORMED_OBJECT {
            get {
                return ResourceManager.GetString("ERR_MALFORMED_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock must be held before make changes to the repository.
        /// </summary>
        internal static string ERR_NO_LOCK {
            get {
                return ResourceManager.GetString("ERR_NO_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventAttribute cannot be applied on non virtual method.
        /// </summary>
        internal static string ERR_NOT_VIRTUAL {
            get {
                return ResourceManager.GetString("ERR_NOT_VIRTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lock assigned to the given id.
        /// </summary>
        internal static string LOCK_NOT_HELD {
            get {
                return ResourceManager.GetString("LOCK_NOT_HELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquire lock for &quot;{0}&quot; by owner &quot;{1}&quot;.
        /// </summary>
        internal static string LOG_ACQUIRE_LOCK {
            get {
                return ResourceManager.GetString("LOG_ACQUIRE_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock (&quot;{0}&quot;) acquisition for owner &quot;{1}&quot; timed out after: {2}ms.
        /// </summary>
        internal static string LOG_ACQUIRE_LOCK_TIMEOUT {
            get {
                return ResourceManager.GetString("LOG_ACQUIRE_LOCK_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found cache entry for view: &quot;{0}&quot;.
        /// </summary>
        internal static string LOG_CACHE_ENTRY_FOUND {
            get {
                return ResourceManager.GetString("LOG_CACHE_ENTRY_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching disabled.
        /// </summary>
        internal static string LOG_CACHING_DISABLED {
            get {
                return ResourceManager.GetString("LOG_CACHING_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw view (&quot;{0}&quot;) cannot be created: &quot;{1}&quot;.
        /// </summary>
        internal static string LOG_CANNOT_CREATE_RAW_VIEW {
            get {
                return ResourceManager.GetString("LOG_CANNOT_CREATE_RAW_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow &quot;{0}&quot; cannot be materialized: &quot;{1}&quot;.
        /// </summary>
        internal static string LOG_CANNOT_MATERIALIZE {
            get {
                return ResourceManager.GetString("LOG_CANNOT_MATERIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating interceptor for view: &quot;{0}&quot;.
        /// </summary>
        internal static string LOG_CREATE_INTERCEPTOR {
            get {
                return ResourceManager.GetString("LOG_CREATE_INTERCEPTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating raw view for: &quot;{0}&quot;.
        /// </summary>
        internal static string LOG_CREATE_RAW_VIEW {
            get {
                return ResourceManager.GetString("LOG_CREATE_RAW_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &quot;{0}&quot; for flow &quot;{1}&quot; cannot be saved: &quot;{2}&quot;.
        /// </summary>
        internal static string LOG_EVENT_NOT_SAVED {
            get {
                return ResourceManager.GetString("LOG_EVENT_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured when processing event (&quot;{0}&quot;) for &quot;{1}&quot;: &quot;{2}&quot;.
        /// </summary>
        internal static string LOG_EVENT_PROCESSOR_ERROR {
            get {
                return ResourceManager.GetString("LOG_EVENT_PROCESSOR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} event(s) processed for: &quot;{1}&quot;.
        /// </summary>
        internal static string LOG_EVENTS_PROCESSED {
            get {
                return ResourceManager.GetString("LOG_EVENTS_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to release lock &quot;{0}&quot; that doesn&apos;t belong to owner &quot;{1}&quot;.
        /// </summary>
        internal static string LOG_FOREIGN_LOCK_RELEASE {
            get {
                return ResourceManager.GetString("LOG_FOREIGN_LOCK_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing database.
        /// </summary>
        internal static string LOG_INIT_SCHEMA {
            get {
                return ResourceManager.GetString("LOG_INIT_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting new event (&quot;{0}&quot;) for view: &quot;{1}&quot;.
        /// </summary>
        internal static string LOG_INSERT_EVENT {
            get {
                return ResourceManager.GetString("LOG_INSERT_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid event id (&quot;{0}&quot;) for view &quot;{1}&quot;.
        /// </summary>
        internal static string LOG_INVALID_EVENT_ID {
            get {
                return ResourceManager.GetString("LOG_INVALID_EVENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View (&quot;{0}&quot;) layout changed since the last update.
        /// </summary>
        internal static string LOG_LAYOUT_MISMATCH {
            get {
                return ResourceManager.GetString("LOG_LAYOUT_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release lock for &quot;{0}&quot; by owner &quot;{1}&quot;.
        /// </summary>
        internal static string LOG_RELEASE_LOCK {
            get {
                return ResourceManager.GetString("LOG_RELEASE_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaying events for view: &quot;{0}&quot;.
        /// </summary>
        internal static string LOG_REPLAY_EVENTS {
            get {
                return ResourceManager.GetString("LOG_REPLAY_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema initialized.
        /// </summary>
        internal static string LOG_SCHEMA_INITIALIZED {
            get {
                return ResourceManager.GetString("LOG_SCHEMA_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating cache item for view: &quot;{0}&quot;.
        /// </summary>
        internal static string LOG_UPDATE_CACHE {
            get {
                return ResourceManager.GetString("LOG_UPDATE_CACHE", resourceCulture);
            }
        }
    }
}
